### ISSUE TITLE
[NCBI-Disease] TypeError: train_generative_model() takes 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by yongzx** [BatsResearch/safranchik-aaai20-code#10]
File: `safranchik-aaai20-code/NCBI-Disease/train_generative_models.py`

Error details:
```
Traceback (most recent call last):
  File "train_generative_models.py", line 494, in <module>
    nb, train_data, dev_data, epochs, gen_label_to_ix, LearningConfig())
TypeError: train_generative_model() takes 5 positional arguments but 6 were given
```

**Comment by safranchik** [comment]
Hello!

What version of Wiser are you currently employing? This repo is compatible with [wiser@v0.1](https://github.com/BatsResearch/wiser/releases/tag/v0.1). However, if you'd like to use the latest version of Wiser, I recommend taking a look at the `util.py` file.

You may find the updated `train_generative_model` method defined on line 64 of the [util.py](https://github.com/BatsResearch/wiser/blob/0ea47ec6211e2d779f34aebd847a5a11018cb6d7/wiser/generative/util.py#L64) file. It no longer takes `epochs` as an argument. Instead, you can define the epochs in the config object that you pass to the method.

For instance, you can define your config object as:
`config = labelmodels.LearningConfig()`
`config.epochs=5`

And then call `train_generative_model(model, train_data, dev_data, label_to_ix, config)` without the `epochs` argument. The `LearningConfig` object is defined [here](https://github.com/BatsResearch/labelmodels/blob/master/labelmodels/label_model.py).

Let me know if this helps!

**Comment by yongzx** [comment]
> You may find the updated train_generative_model method defined on line 64 of the util.py file. It no longer takes epochs as an argument. Instead, you can define the epochs in the config object that you pass to the method.

Yes it works! Thanks for helping out.
