### ISSUE TITLE
code running time

### ISSUE THREAD

**Issue by zhaoxy92** [BatsResearch/safranchik-aaai20-code#2]
Hi, 

I am trying run your code for NBCI dataset. However, after I have the result of majority vote, the program has been running for a while. Could you please let me know how long it might take? Thank you!

**Comment by safranchik** [comment]
Hello,

Given that the NCBI is one of the largest datasets, the code to run our model takes a while. Applying the tagging and linking rules, in addition to training the generative model can take between 3 and 10 hours on a CPU, whereas training the neural network depends on your processor and GPU.

Using an Nvidia GTX 1660, it took us approximately 4 hours to train the discriminative neural model.

Hope that helps!

Esteban

**Comment by zhaoxy92** [comment]
Thank you for letting me know.

**Comment by thak123** [comment]
How to run generative model on GPU as I see the current setup runs on CPU only.

I tried to put the tensors from labelmodels to GPU  but get the inconsistent GPU/CPU tensor error.
Few of the tensors are still on CPU which I am not able to find.
