### ISSUE TITLE
No module named 'wiser.discriminative'

### ISSUE THREAD

**Issue by zhaoxy92** [BatsResearch/safranchik-aaai20-code#3]
Hi,

When I tried to run train_discriminative_models.py, it have the error saying "No module named wiser.discriminative". Looks like wiser does not have a discriminative module. Could you please tell me how to fix that?

**Comment by safranchik** [comment]
Hello,

Apologies for the delay. In your requirements.txt file, can you please replace the last line with 
``git+git://github.com/BatsResearch/wiser@84a453784d3f8d34fe09780c21f18d7d6989d993``.

That should install a previous version of wiser that contains the discriminative module. 
Then, removing the previous version of wiser and reinstalling the requirements should fix your issue.

We will be releasing a patch containing a correction to this issue. Thank you for bringing it up!

Esteban

**Comment by zhaoxy92** [comment]
Thank you!

**Comment by safranchik** [comment]
Closing this issue
