### ISSUE TITLE
Still No module named "wiser.discriminative"

### ISSUE THREAD

**Issue by zhaoxy92** [BatsResearch/safranchik-aaai20-code#5]
Hi, earlier I submitted an issue mentioning this error when I tried to run "train_discriminative_model.py".  You told me that I need to replace the last in the requirements.txt with the following:
``git+git://github.com/BatsResearch/wiser@84a453784d3f8d34fe09780c21f18d7d6989d993``.

However, after I did it and reinstalled the library, this error is still there. Any other ways to fix it? Thanks.

**Comment by safranchik** [comment]
Hello,

We've released a patch that fixes this issue. If editing the requirements.txt file doesn't work, consider downloading the latest version of the repo and re-installing the requirements on a new virtual environment. That should do the trick.

Esteban

**Comment by zhaoxy92** [comment]
Thank you, it worked!
