### ISSUE TITLE
How did you run it on GPU. as I see the current setup runs on CPU only. Am I missing something

### ISSUE THREAD

**Issue by safranchik** [BatsResearch/safranchik-aaai20-code#6]
How did you run it on GPU. as I see the current setup runs on CPU only. Am I missing something
?

_Originally posted by @thak123 in https://github.com/BatsResearch/safranchik-aaai20-code/issues/2#issuecomment-630915776_

**Comment by safranchik** [comment]
The current version of WISER does not run on GPU. During development, we tested a version of the linked HMM generative model on the GPU. However, we didn't consider releasing it publicly as it was significantly slower than training it on the CPU, mostly due to matrix sparsity.

I hope that helps!

**Comment by thak123** [comment]
Yes... thanks for the comment. I thought it would take a lot of time to train but the demo  example(generative model) finished within 10 mins. So its still fine.
