### ISSUE TITLE
lambda_link has no 'ABS'

### ISSUE THREAD

**Issue by lephong** [BatsResearch/safranchik-aaai20-code#7]
Hi. I think in the code a lambda_link can get 0 or 1 rather than 3 values as in the paper. Is that documented somewhere, together with the formula of p(lambda_link | p_i, p_{i-1})?

**Comment by lephong** [comment]
I think I get the answer: -1, 0, 1 mean DIFF, ABS, SAME (seems like DIFF is very rare)

**Comment by stephenbach** [comment]
Hi Phong,
That's all correct!
